---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openweb-ui-deployment
  labels:
    app: openweb-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openweb-ui
  template:
    metadata:
      labels:
        app: openweb-ui
    spec:
      containers:
        - name: openweb-ui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - containerPort: 8080
          # resources:
          #   limits:
          #     memory: 128Mi
          #     cpu: 250m
          env:
            - name: OLLAMA_BASE_URL
              value: http://ollama-models-store:11434
