---
apiVersion: v1
kind: Service
metadata:
  name: openweb-ui-service
  labels:
    app: openweb-ui
spec:
  type: ClusterIP
  selector:
    app: openweb-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
