---
version: "3"

tasks:
  cluster-create:
    cmds:
      - ctlptl apply -f Cluster.yaml
      - helm repo add nginx-stable https://helm.nginx.com/stable && helm repo update
      - helm install nginx-ingress nginx-stable/nginx-ingress --namespace nginx-ingress --create-namespace

  cluster-delete:
    cmds:
      - ctlptl delete -f Cluster.yaml

  clean:
    cmds:
      - task: cluster-delete
